### ISSUE TITLE
Disabled on Edit mode

### ISSUE THREAD

**Issue by dpogni** [kevinweber/aem-front-extension#1]
Can you consider an option to disable the author edit mode?

My reason is that it's a very JS heavy page and takes a long time to load. I'd rather have more control over certain types of pages.

This could also be solved by having a more general option to disable browser sync per-each chrome tab.

**Comment by kevinweber** [comment]
The just published version 0.1 allows you to enable/disable page reload for individual tabs. You can also define whether all pages should reload by default or not.
1. Double-click on the extension's icon (next to Chrome's search bar) opens the options panel. New tabs always use the global default.
2. A single click overrides the global default for the current tab.

However, I leave this ticket open because there's no option yet to configure whether pages should reload for certain paths or page types (e.g. a page in edit mode).

**Comment by kevinweber** [comment]
Hi Dean,
the just published version 2.1 gives you an input field where the default paths can be overridden. If you don't want AEM Front to reload any page that has a path starting with "editor.html", you can override the default with `content/`, for example.
